### ISSUE TITLE
Status code 400 on set 2fa code

### ISSUE THREAD

**Issue by dez64ru** [foxt/icloud.js#1]
Hello, this library still WIP?
I always get error when i set security code

```js
const iCloud = require('icloudjs').default
const path = require('path')
const prompt = require('prompt')

const icloud = new iCloud({
    username: "my_apple_id",
    password: "my_password",
    saveCredentials: true,
    trustDevice: true,
    dataDirectory: path.resolve('./tmp/')
});

(async() => {
  await icloud.authenticate()

  if (icloud.status === "MfaRequested") {
    const code =  await prompt.get(['2fa code'])
    await icloud.provideMfaCode(code)
  }

  await icloud.awaitReady;
  console.log("Hello, " + icloud.accountInfo.dsInfo.fullName)
})();
```

<details>
<summary>error</summary>

![Screenshot 2022-11-18 at 01 16 27](https://user-images.githubusercontent.com/32451886/202561590-4f8a0c67-87c5-46e5-94e8-fb123bb6b42d.png)
</details>

PS: also tried enter code without any space

**Comment by foxt** [comment]
> Hello, this library still WIP?

Yes, however authenticaation & read only access to certain services (if you'd like a service prioritised please let me know)

A 400 error code usually indicates that the code was incorrect. I've just published a 1.2.1 version to NPM which should give you more details about why it failed.

Thanks

**Comment by dez64ru** [comment]
@foxt 

<details>
<summary>📹 1.2.1</summary>

https://user-images.githubusercontent.com/32451886/202631248-7789dc41-2ecb-4a0d-bf26-4361d3a8f0ed.mov
</details>



<details>
<summary>PS: Also i tried convert input to number, and got another error</summary>

<img width="874" alt="Screenshot 2022-11-18 at 09 58 45" src="https://user-images.githubusercontent.com/32451886/202631573-83f95eea-6d34-49d9-b6b1-af9a5d2f744f.png">
</details>

**Comment by dez64ru** [comment]
> Yes, however authenticaation & read only access to certain services (if you'd like a service prioritised please let me know)

Actually i want help you with this library :)
Now i write screensaver for my android tv, and i want write calendar and photos services for your library.

**Comment by foxt** [comment]
Are you sure 'prompt' is directly returning the value input by the user?
had a quick look at the docs and it might be something like

    await icloud.provideMfaCode(code["2fa code"])

**Comment by dez64ru** [comment]
@foxt Yeah, you right. Thanks a lot!

![Screenshot 2022-11-18 at 11 34 37](https://user-images.githubusercontent.com/32451886/202646767-179508ba-2512-42cf-9761-adfd62608ffa.png)
