### ISSUE TITLE
How to import the API classes (noob)

### ISSUE THREAD

**Issue by costa** [foxt/icloud.js#22]
This is probably a noob's question (I've been forced into TS just recently): if I'd like to operate on objects provided by the API, e.g. `getPhotos()` returning `Array<iCloudPhotoAsset>` — and I seem to fail to `import { iCloudPhotoAsset } from ...` anywhere... I really have no idea if it's something I'm missing with TS, or the package might be missing something — the latter seems crazy to me, coming from all the other languages, but I'll appreciate an advice.

**Comment by foxt** [comment]
Thanks for catching this, seems like those types arent exported.

**Comment by costa** [comment]
Thanks, so, how do I import, say, `iCloudPhotoAsset`?

**Comment by costa** [comment]
> Thanks, so, how do I import, say, `iCloudPhotoAsset`?

@foxt ?
